name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      # -- Backend Steps --
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install
      - name: Test Backend
        run: |
          cd backend
          npm test  # or npm run test if you have a test script

      # -- Frontend Steps --
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install
      - name: Build Frontend
        run: |
          cd frontend
          npm run build
      - name: Test Frontend
        run: |
          cd frontend
          npm test  # or npm run test if you have a test script
